run:
	py manage.py runserver

mig_m:
	py manage.py makemigrations CompanyManagement

mig:
	py manage.py migrate CompanyManagement

lib:
	pip install -r requirement.txt

shell:
	py manage.py shell

Note:
	py -m venv [name-project]
	[name-project]\Scripts\activate.bat

	py -m pip install Django==3.2.10

	django-admin startproject [name-project]
	django-admin startapp [name-app]

 